name: namaz_vakitleri
description: "Namaz Vakitleri ve Kıble Pusulası Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Prayer times calculation
  adhan: ^2.0.0+1

  # Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Notifications / Alarms
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0

  # Compass sensor - qibla calculated manually
  flutter_compass: ^0.8.0

  # Permissions
  permission_handler: ^11.3.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
